// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package ports

// users login credentials
type LoginUser struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// message
type Message struct {
	Msg string `json:"msg"`
}

// logged in user details
type User struct {
	Name     string `json:"name"`
	Username string `json:"username"`
}

// LoginUserJSONBody defines parameters for LoginUser.
type LoginUserJSONBody LoginUser

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody LoginUserJSONBody
